---
title: Ohio Popcorn

output:
  pdf_document:
#    toc: true
#    toc_depth: 3
    includes:
      in_header: OPmusicIncludes.tex
---
\lhead{}
\chead{}
\rhead{\thepage}
\lfoot{}
\cfoot{}
\rfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\hypersetup{linkcolor=black}
\cleardoublepage
\phantomsection
\addcontentsline{toc}{section}{Contents}

\tableofcontents


```{r songs,echo=FALSE}
#
require(plyr)
#order by set when making a set list
by.set<-FALSE

#music part or formatting
types<-if(FALSE)c('Chords','Lyrics','Lead','Rhythm','Bass') else c('Chords','Lyrics')

#datapath<-'/home/jallen/Music/'
set.paths('OhioPopcorn')#

####
#Functions
####
simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}

stripSlash <- function(x) {
  s <- strsplit(x, "\\/")[[1]]
  paste(substring(s, 1,1), substring(s, 2),
      sep="", collapse="")
}

song.pop<-function(type,band,song){
  if(file.exists(paste0(datapath,band,song,type,'.pdf'))){
    cat(paste0('\\includepdf[pages=-,pagecommand={\\pagestyle{fancy}},addtotoc={1,subsubsection,2,',
               type,',',datapath,
               band,
               song,
               type,
               '}]{',datapath,
               band,
               song,
               type,'.pdf}\n\n'))
    }
}

####
#End Functions
####

#read songlist
songs<-read.csv(paste0(rootpath,'OPsongs.csv'))
#create dataframe
songs.df<-data.frame(page=as.numeric(songs$page),
                     song=sapply(as.character(songs$song),simpleCap),
                     band=factor(songs$band),
                     set=as.numeric(songs$set),
                     number=as.numeric(songs$number),
                     row.names=NULL)
#remove spaces in song and band
songs.df$song.c<-gsub("[[:space:]]", "", songs.df$song)
songs.df$band.c<-gsub("[[:space:]]", "", songs.df$band)
#remove slashes
songs.df$band.c<-apply(songs.df,1,function(x)stripSlash(x[['band.c']]))

#order songs by set or band and song
songs.df<-if(by.set){
  songs.df[order(songs.df$set,songs.df$number,songs.df$page,songs.df$band,songs.df$song),]
} else songs.df[order(songs.df$band,songs.df$song),]


```


```{r sets,echo=FALSE,warning=FALSE,message=FALSE,results='asis'}
#iterate through songs.df based on whether it is a set list or not
l_ply(if(by.set) seq(1,max(songs.df$set)) else 1,
      .fun=function(set){
        if(by.set)cat('\\section{Set',set,'}\n\n')
        songs.list<-if(by.set) songs.df[songs.df$set==set,] else songs.df
        apply(songs.list,1,function(x){
          cat('\\invisiblesubsection{',x[['song']],'-',x[['band']],'- Page',x[['page']],'}\n\n')
          l_ply(types,
                .fun=function(type){
                  song.pop(type,x[['band.c']],x[['song.c']])
                  })
          }
          )
        }
      )
```

